### ISSUE TITLE
Index.html is empty

### ISSUE THREAD

**Issue by JDHess** [JDHess/collab-practice#1]
The index page needs some content

**Comment by Msolis1** [comment]
okay ill help with that

**Comment by Msolis1** [comment]
I cloned your repository to my VS/desktop

**Comment by JDHess** [comment]
Nice thank you

**Comment by Msolis1** [comment]
on my branch i added the nav, right, left columns and footer. still making detailed cosmetic adjustments thought. I appreciate your patience.

**Comment by JDHess** [comment]
Awesome thank you! Let me know when you want me to merge the branches. No rush.

**Comment by Msolis1** [comment]
do you think he will have us do that someother time as a take home challenge

**Comment by JDHess** [comment]
We'll probably go over it in class, and do it as a daily challenge.

**Comment by JDHess** [comment]
I'll check

**Comment by JDHess** [comment]
Daily challenge: "Create a new pull request for your take-home branch" so yes we will do it for the daily challenge

**Comment by JDHess** [comment]
Please create a merge request and request a review.
